# -*- coding: utf-8 -*-
"""modelling

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QAV6TqrB-o43FbJ5_T0ErlAQ4jCJOIZ3

# Modeling Biasa Tanpa Tuning
"""

!pip install mlflow dagshub scikit-learn pandas seaborn matplotlib

import os
import mlflow
import dagshub
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from automate_davida import preprocess_data

X_train, X_test, y_train, y_test = preprocess_data(
    data_path="gender_classification_v7.csv"
)

import argparse
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import mlflow
import mlflow.sklearn

def train(data_path):
    df = pd.read_csv(data_path)
    df = df.drop_duplicates()

    df['gender'] = df['gender'].map({'Male': 0, 'Female': 1})

    X = df.drop('gender', axis=1)
    y = df['gender']

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )

    scaler = StandardScaler()
    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)

    mlflow.autolog()

    with mlflow.start_run():
        model = LogisticRegression()
        model.fit(X_train, y_train)

        acc = accuracy_score(y_test, model.predict(X_test))
        print("Accuracy:", acc)

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument(
    "--data_path",
    type=str,
    default="gender_classification_v7.csv")
    args, _ = parser.parse_known_args()

    train(args.data_path)

os.environ["MLFLOW_TRACKING_USERNAME"] = "david123410"
os.environ["MLFLOW_TRACKING_PASSWORD"] = "0cde087c9642909f0a12eedf582fbbbf1d113b04"

dagshub.init(
    repo_owner="david123410",
    repo_name="Eksperimen_SML_David",
    mlflow=True
)

mlflow.set_experiment("Gender_Classification_Advanced")